Remove `pip3` upgrade to avoid conflict
Originally, we have to upgrade the pip3 to the latest version. However, that turns out to be a problem down the road when installing cortx-py-utils. Actually, pip3 has been included with the Python installer since versions 3.4 for Python 3.

Regarding how to reproduce the problem:
The cortx-py-utils installation (written here https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md) will fail when installing`dependent python package`. 
The error is:
```sh
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.6/site-packages (from idna-ssl>=1.0->aiohttp==3.6.1->-r python_requirements.txt (line 1)) (2.10)
Using legacy 'setup.py install' for python-crontab, since package 'wheel' is not installed.
Using legacy 'setup.py install' for PyYAML, since package 'wheel' is not installed.
Using legacy 'setup.py install' for idna-ssl, since package 'wheel' is not installed.
Installing collected packages: typing-extensions, multidict, yarl, pynacl, numpy, kiwisolver, idna-ssl, elasticsearch, cycler, cryptography, bcrypt, async-timeout, toml, schematics, PyYAML, python-crontab, python-consul, paramiko, networkx, matplotlib, elasticsearch-dsl, confluent-kafka, configparser, aiohttp
    Running setup.py install for idna-ssl ... done
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.1
    Uninstalling cryptography-3.1:
      Successfully uninstalled cryptography-3.1
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
The reason is, the newly upgraded pip3 failed to uninstall `PyYAML` for some reason. However, if we don't upgrade the pip3, it can uninstall `PyYAML` just fine. 
The default pip3 is at version 9.0.3
The upgraded pip3 is at version 21.1.3 

I am not sure why that pip3 version causes this problem, but I've tested and investigated this matter in 6 different nodes (hosted by Chameleon cluster) and the solution is just simply by avoiding the pip3 upgrade. 

Let me know if you guys have any questions. I can show you how to reproduce this and give you access to the server.